// Traductions anglaises de l'interface (texte français → anglais).
// Fichier généré : chaque L("…") du code doit avoir sa ligne ici.

let EN: [String: String] = [
    "ADA'S demandera Face ID à chaque ouverture. Le Coffre est toujours protégé, même si cette option est désactivée.": "ADA'S will ask for Face ID every time it opens. The Vault is always protected, even when this option is off.",
    "ADA'S est verrouillée.": "ADA'S is locked.",
    "Accueil": "Home",
    "Aide": "Help",
    "Ajouter à une playlist": "Add to a playlist",
    "Ajoutez des morceaux depuis l'accueil : ⋯ puis « Ajouter à une playlist ».": "Add songs from the Home tab: tap ⋯ then “Add to a playlist”.",
    "Ajouté aux favoris.": "Added to favorites.",
    "Ajouté à « {name} ».": "Added to “{name}”.",
    "Aléatoire": "Shuffle",
    "Analyse du lien…": "Analyzing link…",
    "Annuler": "Cancel",
    "Annulé": "Cancelled",
    "Annulé.": "Cancelled.",
    "Assemblage…": "Merging…",
    "Aucun favori": "No favorites",
    "Aucun format lisible sur iPhone n’est proposé pour ce contenu (la plateforme ne fournit que du WebM/VP9). Essayez le mode Audio ou une autre qualité.": "No iPhone-compatible format is offered for this content (the platform only provides WebM/VP9). Try Audio mode or another quality.",
    "Aucun lien trouvé dans le texte copié.": "No link found in the copied text.",
    "Aucun morceau": "No songs",
    "Aucun résultat": "No results",
    "Aucune lecture en cours": "Nothing playing",
    "Aucune sauvegarde trouvée dans l'app Fichiers › ADA'S.": "No backup found in Files › ADA'S.",
    "Automatique (système)": "Automatic (system)",
    "Bloqué : aucune progression pendant trop longtemps.": "Stuck: no progress for too long.",
    "Ce direct n’a pas encore commencé.": "This live stream hasn't started yet.",
    "Ce lien ne correspond pas à une vidéo prise en charge.": "This link isn't a supported video.",
    "Ce morceau est déjà léger : rien à gagner.": "This song is already small: nothing to gain.",
    "Ce site bloque les téléchargements hors navigateur pour ce contenu. Réessayez plus tard.": "This site blocks downloads outside the browser for this content. Try again later.",
    "Ce site livre la vidéo dans un format (MPEG-TS/HLS) que ADA ne sait pas encore convertir sur téléphone.": "This site delivers the media in a format (MPEG-TS/HLS) that ADA can't convert on a phone yet.",
    "Chargement…": "Loading…",
    "Cherchez un titre ou un artiste": "Look for a song or an artist",
    "Clair": "Light",
    "Classement indisponible": "Chart unavailable",
    "Coffre": "Vault",
    "Coffre verrouillé": "Vault locked",
    "Coffre verrouillé : identification refusée.": "Vault locked: identification failed.",
    "Coller un lien": "Paste a link",
    "Comment cacher un morceau ?": "How do I hide a song?",
    "Comment importer une musique ?": "How do I import a song?",
    "Comment réduire la taille d'un morceau ?": "How do I make a song smaller?",
    "Comment écouter sur une enceinte ou une TV ?": "How do I play on a speaker or TV?",
    "Compresser": "Compress",
    "Compression de « {title} »…": "Compressing “{title}”…",
    "Compression déjà en cours pour ce morceau.": "This song is already being compressed.",
    "Compression impossible (stockage).": "Compression failed (storage).",
    "Compression impossible pour ce fichier.": "This file can't be compressed.",
    "Compressé : {size} (−{saved}).": "Compressed: {size} (−{saved}).",
    "Confidentialité": "Privacy",
    "Connexion requise pour ce contenu (restreint, sensible ou réservé aux comptes connectés). Connectez-vous au site dans l’onglet Navigateur si vous y avez accès.": "Sign-in required for this content (restricted, sensitive or members-only). Sign in to the site in the Browser tab if you have access.",
    "Connexion rétablie : reprise des imports.": "Back online: imports are resuming.",
    "Contenu en direct (live) : ADA ne télécharge pas les directs en cours ou à venir. Réessayez quand la rediffusion sera disponible.": "Live content: ADA doesn't import ongoing or upcoming live streams. Try again when the replay is available.",
    "Contenu introuvable ou supprimé (lien expiré ou incorrect).": "Content not found or deleted (expired or wrong link).",
    "Contenu non disponible dans votre pays.": "Content not available in your country.",
    "Contenu protégé par DRM : téléchargement impossible.": "DRM-protected content: can't be downloaded.",
    "Copiez d'abord un lien YouTube (ou d'un autre site), puis touchez « Coller un lien ».": "First copy a YouTube link (or one from another site), then tap “Paste a link”.",
    "Copiez un lien YouTube puis touchez « Coller un lien », ou cherchez un titre dans l'onglet Rechercher.": "Copy a YouTube link and tap “Paste a link”, or look for a song in the Search tab.",
    "Créer": "Create",
    "Dans YouTube (ou un autre site), touchez « Partager » puis « Copier le lien ». Revenez dans ADA'S et touchez « Coller un lien » sur l'accueil. Vous pouvez aussi chercher un titre dans l'onglet Rechercher.": "In YouTube (or another site), tap “Share” then “Copy link”. Come back to ADA'S and tap “Paste a link” on the Home tab. You can also look for a song in the Search tab.",
    "Dans l'app Fichiers › Sur mon iPhone › ADA'S. Les morceaux du Coffre n'y apparaissent pas.": "In the Files app › On My iPhone › ADA'S. Songs in the Vault don't appear there.",
    "Date d'ajout": "Date added",
    "Déjà dans le Coffre.": "Already in the Vault.",
    "Déjà dans « {name} ».": "Already in “{name}”.",
    "Déjà téléchargé": "Already downloaded",
    "Déjà téléchargé (fichier présent).": "Already downloaded (file present).",
    "Délai de connexion dépassé.": "Connection timed out.",
    "Démarrage…": "Starting…",
    "Désactivé": "Off",
    "Déverrouiller": "Unlock",
    "Déverrouiller ADA'S": "Unlock ADA'S",
    "Effacer": "Clear",
    "En attente": "Queued",
    "En attente du réseau": "Waiting for network",
    "En cours de lecture": "Now Playing",
    "En pause": "Paused",
    "En pause.": "Paused.",
    "Envoyer un avis": "Send feedback",
    "Erreur": "Error",
    "Erreur de certificat SSL : vérifiez la date et l’heure du téléphone.": "SSL certificate error: check the phone's date and time.",
    "Essayez avec d'autres mots.": "Try different words.",
    "Faites une capture de cet écran et envoyez-la : elle indique exactement ce qui bloque.": "Take a screenshot of this screen and send it: it shows exactly what went wrong.",
    "Favori": "Favorite",
    "Favoris": "Favorites",
    "Fermer": "Close",
    "Fichier introuvable (supprimé ou déplacé).": "File not found (deleted or moved).",
    "Finalisation de la vidéo…": "Finishing…",
    "Genres": "Genres",
    "Général": "General",
    "Historique": "History",
    "Identifiez-vous avec Face ID pour voir vos morceaux privés.": "Use Face ID to see your private songs.",
    "Ignorer les doublons": "Skip duplicates",
    "Import lancé : {title}": "Import started: {title}",
    "Imports": "Imports",
    "Imports en cours": "Importing",
    "Imports simultanés": "Simultaneous imports",
    "Importé : {title}": "Imported: {title}",
    "Impossible de ranger ce fichier dans le Coffre.": "Couldn't move this file to the Vault.",
    "Impossible de sortir ce fichier du Coffre.": "Couldn't take this file out of the Vault.",
    "Impossible d’écrire le fichier sur le téléphone.": "Couldn't write the file to the phone.",
    "J'utilise ADA'S pour importer et écouter ma musique. Essayez-la !": "I use ADA'S to import and listen to my music. Give it a try!",
    "JavaScript (YouTube)": "JavaScript (YouTube)",
    "La bibliothèque et les playlists actuelles seront remplacées par celles de la sauvegarde.": "Your current library and playlists will be replaced by the backup.",
    "La connexion a été interrompue.": "The connection was interrupted.",
    "La lecture se met en pause à {time}.": "Playback will pause at {time}.",
    "La lecture sera mise en pause dans {minutes} min.": "Playback will pause in {minutes} min.",
    "La plateforme limite les requêtes (429). ADA réessaiera dans un instant.": "The platform is rate-limiting requests (429). ADA will try again in a moment.",
    "La plateforme rencontre un problème temporaire (erreur serveur).": "The platform has a temporary problem (server error).",
    "La qualité demandée n’existe pas pour cette vidéo. Choisissez « Meilleure ».": "The requested quality doesn't exist for this video. Choose “Best”.",
    "La sauvegarde (sans les fichiers audio) va dans l'app Fichiers › ADA'S. Gardez-la ou envoyez-la sur un autre iPhone pour tout retrouver.": "The backup (without the audio files) is saved in Files › ADA'S. Keep it, or send it to another iPhone to get everything back.",
    "Langue": "Language",
    "Langue du téléphone": "Phone language",
    "Le moteur d'import n'a pas démarré": "The import engine didn't start",
    "Le moteur démarre, réessayez dans un instant.": "The engine is starting, try again in a moment.",
    "Lecteur": "Player",
    "Les morceaux du Coffre sont cachés de la bibliothèque et de l'app Fichiers. Le Coffre se reverrouille dès que vous le quittez.": "Songs in the Vault are hidden from your library and from the Files app. The Vault locks again as soon as you leave it.",
    "Les morceaux restent dans votre bibliothèque.": "The songs stay in your library.",
    "Libre : {free}": "Free: {free}",
    "Lien invalide.": "Invalid link.",
    "L’hébergeur a refusé l’accès (403). Désactivez un éventuel VPN, puis réessayez.": "The host refused access (403). Turn off any VPN, then try again.",
    "Ma playlist": "My playlist",
    "Mes playlists": "My playlists",
    "Mettre au Coffre": "Move to Vault",
    "Minuteur de sommeil": "Sleep timer",
    "Minuteur de sommeil : lecture mise en pause.": "Sleep timer: playback paused.",
    "Moteur": "Engine",
    "Moteur d'import": "Import engine",
    "Musique : {used}": "Music: {used}",
    "Nom": "Name",
    "Nom de la nouvelle playlist": "New playlist name",
    "Nom de la playlist": "Playlist name",
    "Nouvelle playlist": "New playlist",
    "Nouvelle tentative…": "Retrying…",
    "Nouvelles tentatives": "Automatic retries",
    "OK": "OK",
    "Ouvrez le lecteur (touchez le morceau en bas de l'écran) puis le bouton AirPlay.": "Open the player (tap the song at the bottom of the screen), then the AirPlay button.",
    "Ouvrir le Coffre d'ADA'S": "Open the ADA'S Vault",
    "Où sont mes fichiers ?": "Where are my files?",
    "Partager": "Share",
    "Partager ADA'S": "Share ADA'S",
    "Pas de connexion internet (adresse introuvable).": "No internet connection (address not found).",
    "Pas de connexion internet : les imports reprendront tout seuls.": "No internet connection: imports will resume on their own.",
    "Playlist": "Playlist",
    "Playlists": "Playlists",
    "Protégé par Face ID": "Protected by Face ID",
    "Publication « photo » TikTok : lecture impossible pour le moment (TikTok a peut-être bloqué la demande). Réessayez plus tard.": "TikTok “photo” post: can't be read right now (TikTok may have blocked the request). Try again later.",
    "Quels liens puis-je importer ?": "Which links can I import?",
    "Rangez ici vos morceaux privés : ⋯ puis « Mettre au Coffre » sur l'accueil.": "Keep your private songs here: tap ⋯ then “Move to Vault” on the Home tab.",
    "Rangé dans le Coffre.": "Moved to the Vault.",
    "Recherche impossible": "Search failed",
    "Rechercher": "Search",
    "Recherche…": "Searching…",
    "Renommer": "Rename",
    "Restaurer": "Restore",
    "Restaurer la sauvegarde ?": "Restore the backup?",
    "Retirer": "Remove",
    "Retirer des favoris": "Remove from favorites",
    "Retiré des favoris.": "Removed from favorites.",
    "Récentes": "Recent",
    "Récents": "Recent",
    "Réessayer": "Try again",
    "Réglages": "Settings",
    "Sauvegarde": "Backup",
    "Sauvegarde enregistrée dans l'app Fichiers › ADA'S.": "Backup saved in Files › ADA'S.",
    "Sauvegarde impossible (stockage indisponible).": "Backup failed (storage unavailable).",
    "Sauvegarde restaurée.": "Backup restored.",
    "Sauvegarder": "Back up",
    "Sombre": "Dark",
    "Sorti du Coffre : de retour dans la bibliothèque.": "Out of the Vault: back in your library.",
    "Sortir du Coffre": "Remove from Vault",
    "Stockage du téléphone plein : libérez de l’espace puis réessayez.": "Phone storage full: free up space and try again.",
    "Supprimer": "Delete",
    "Supprimer ce morceau ?": "Delete this song?",
    "Supprimer la playlist": "Delete playlist",
    "Supprimer la playlist ?": "Delete this playlist?",
    "Supprimé ou déplacé": "Deleted or moved",
    "Supprimé.": "Deleted.",
    "Sur l'accueil, touchez ⋯ sur le morceau puis « Mettre au Coffre ». Il n'apparaît plus que dans le Coffre, protégé par Face ID.": "On the Home tab, tap ⋯ on the song then “Move to Vault”. It then only appears in the Vault, protected by Face ID.",
    "Taille (plus gros)": "Size (largest)",
    "Tendances": "Trending",
    "Terminé": "Done",
    "Thème": "Theme",
    "Titre, artiste, lien…": "Song, artist, link…",
    "Top titres": "Top songs",
    "Touchez ⋯ puis « Compresser ». Si le gain est trop faible, le fichier d'origine est gardé.": "Tap ⋯ then “Compress”. If the saving is too small, the original file is kept.",
    "Touchez ⋯ puis « Favori » sur un morceau pour le retrouver ici.": "Tap ⋯ then “Favorite” on a song to find it here.",
    "Tout": "All",
    "Tout lire": "Play all",
    "Tout mettre en pause": "Pause all",
    "Tout reprendre": "Resume all",
    "Trier par": "Sort by",
    "Téléchargement…": "Downloading…",
    "Verrouiller ADA'S à l'ouverture": "Lock ADA'S when opening",
    "Version {version}": "Version {version}",
    "Vidéo privée : votre compte n’y a pas accès.": "Private video: your account doesn't have access.",
    "Vidéo soumise à une vérification d’âge. Connectez-vous au site dans l’onglet Navigateur si vous y êtes autorisé.": "Age-restricted video. Sign in to the site in the Browser tab if you're allowed to watch it.",
    "Vos musiques apparaîtront ici.": "Your music will appear here.",
    "Vos recherches récentes apparaîtront ici.": "Your recent searches will appear here.",
    "Votre musique, importée et rangée.": "Your music, imported and organized.",
    "Vérifiez votre connexion, puis réessayez.": "Check your connection, then try again.",
    "YouTube demande de confirmer que vous n’êtes pas un robot. Attendez un peu, ou connectez-vous à YouTube dans l’onglet Navigateur puis réessayez.": "YouTube is asking to confirm you're not a robot. Wait a bit, or sign in to YouTube in the Browser tab and try again.",
    "YouTube et la plupart des sites de vidéos ou de musique publics. Les contenus protégés (DRM) ne peuvent pas être importés.": "YouTube and most public video or music sites. Protected (DRM) content can't be imported.",
    "YouTube n’a pas pu être déchiffré avec le moteur JavaScript du téléphone. Réessayez ; si ça persiste, mettez ADA à jour.": "YouTube couldn't be decoded with the phone's JavaScript engine. Try again; if it keeps happening, update ADA.",
    "{count} import(s) lancé(s).": "{count} import(s) started.",
    "{count} morceau(x)": "{count} song(s)",
    "{count} résultat(s)": "{count} result(s)",
    "{count} vues": "{count} views",
    "{minutes} min": "{minutes} min",
    "« {name} » créée.": "“{name}” created.",
    "« {name} » supprimée.": "“{name}” deleted.",
    "« {title} » sera supprimé de l'iPhone.": "“{title}” will be deleted from the iPhone.",
    "À propos": "About",
    "À suivre": "Up Next",
    "Échec": "Failed",
    "Échec : {title}": "Failed: {title}",
    "Écran allumé pendant les imports": "Keep screen on while importing",
]
